
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: CA3F4CEB7486F6668BD6F181D6CA68F608603F641897C20DF217C55FE3F3416F64E665190F35F5CE91CF8F38D5FB78FB96170CE35D755393898FFBDA2F093BF2
//------------------------------------------------------------------------

library com.example.testSoap.wcf;

import 'dart:typed_data';
import 'dart:convert';
import 'dart:io';
import 'package:collection/collection.dart';
import 'package:xml/xml.dart';
import 'package:http/http.dart';
import 'package:uuid/uuid.dart';



import 'dart:collection';

part 'GQBRequestResultHandler.dart';
part 'GQBHelper.dart';
part 'GQBConnectionProvider.dart';
part 'GQBDateTimeParser.dart';

part 'GQBTableColumn.dart';
part 'GQBRowCell.dart';
part 'GQBArrayOfTableColumn.dart';
part 'GQBArrayOfRowCell.dart';
part 'GQBArrayOfstring.dart';

part 'GQBBasicHttpBinding_IDbService.dart';

part 'GQBColumnType.dart';
