
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: CA3F4CEB7486F6668BD6F181D6CA68F608603F641897C20DF217C55FE3F3416F64E665190F35F5CE91CF8F38D5FB78FB96170CE35D755393898FFBDA2F093BF2
//------------------------------------------------------------------------
part of com.example.testSoap.wcf;


class GQBColumnType
{
    final int _value;
    final String _name;

    const GQBColumnType._internal(this._value,this._name);
    toString() => _name;

    int get value=>_value;
    
    static const Integer = GQBColumnType._internal(0,'Integer');
    static const Real = GQBColumnType._internal(1,'Real');
    static const Char = GQBColumnType._internal(2,'Char');
    static const xString = GQBColumnType._internal(3,'String');
    static const DateTime = GQBColumnType._internal(4,'DateTime');
    static const DateInterval = GQBColumnType._internal(5,'DateInterval');

    static GQBColumnType? fromString(String str)
    {
        if (str=="Integer")
            return Integer;
        if (str=="Real")
            return Real;
        if (str=="Char")
            return Char;
        if (str=="String")
            return xString;
        if (str=="DateTime")
            return DateTime;
        if (str=="DateInterval")
            return DateInterval;
        return null;
    }


}

