
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: CA3F4CEB7486F6668BD6F181D6CA68F608603F641897C20DF217C55FE3F3416F64E665190F35F5CE91CF8F38D5FB78FB96170CE35D755393898FFBDA2F093BF2
//------------------------------------------------------------------------
part of com.example.testSoap.wcf;

abstract class  GQBIDateTimeParser
{
    String? getStringFromDate(DateTime? date);
    String? getStringFromDateTime(DateTime? date);
    DateTime? parse(String? value);
}

class GQBDateTimeParser implements GQBIDateTimeParser
{
    static String _fourDigits(int n) {
        int absN = n.abs();
        String sign = n < 0 ? "-" : "";
        if (absN >= 1000) return "$n";
        if (absN >= 100) return "${sign}0$absN";
        if (absN >= 10) return "${sign}00$absN";
        return "${sign}000$absN";
    }

    static String _sixDigits(int n) {
        assert(n < -9999 || n > 9999);
        int absN = n.abs();
        String sign = n < 0 ? "-" : "+";
        if (absN >= 100000) return "$sign$absN";
        return "${sign}0$absN";
    }

    static String _twoDigits(int n) {
        if (n >= 10) return "${n}";
        return "0${n}";
    }

    @override
    String? getStringFromDate(DateTime? date){
        if(date!=null)
        {
            String y =(date.year >= -9999 && date.year <= 9999) ? _fourDigits(date.year) : _sixDigits(date.year);
            String m = _twoDigits(date.month);
            String d = _twoDigits(date.day);
            return "$y-$m-${d}";
        }
        return null;
    }

    @override
    String? getStringFromDateTime(DateTime? date){
        if(date!=null)
        {
            return date.toIso8601String();
        }
        return null;
    }

    @override
    DateTime? parse(String? value) {
        if(value!=null)
        {
            return DateTime.parse(value);
        }
        return null;
    }

}